# Generated by Django 4.2.2 on 2023-10-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0063_alter_graphinterface_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='load_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
