# Generated by Django 4.2.2 on 2024-02-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_alter_graphinterface_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Consumption',
        ),
    ]
